- name: Enable Replication 
  hosts: primaryarray
  connection: local
  collections:
  - purestorage.flasharray
  gather_facts: no


  tasks:
    - name: Enabling replication and setting schedule
      purefa_pgsched:
        name: "{{ group }}" 
        schedule: replication
        enabled: true
        replicate_frequency: 3600
        fa_url: "{{ primary_array }}"
        api_token: "{{ primary_array_token }}"
