- name: restore volume data from protection group snapshot
  hosts: 10.226.224.110
  connection: local
  collections:
  - purestorage.flasharray
  gather_facts: no

  tasks:
    - name:  Restoring volume from the protection group snapshot with suffix app_recovery_CBS
      purefa_pgsnap:
        name: RedDot:apprecoveryCBS
        suffix: 5
        restore: k8s-pvc-e6a7eeb3-9501-4cb4-898d-c49315ac847f 
        target: k8s-pvc-6f34747e-7524-459c-ae74-205ad8d3f5fc
        overwrite: true
        fa_url: 10.226.224.110
        api_token: aa009fd2-7686-7d48-8698-26b7eb2ae841
        state: copy
