- name: restore volume data from protection group snapshot
  hosts: drarray
  connection: local
  collections:
  - purestorage.flasharray
  gather_facts: no

  tasks:
    - name:  Restoring volume from the protection group snapshot with suffix app_recovery_CBS
      purefa_pgsnap:
        name: RedDot:apprecoveryCBS 
     #   suffix: "{{ suff }}"
        suffix: 4
        restore: "{{ restorevolume }}"
        target: "{{ targetvolume }}"
        overwrite: true
        fa_url: "{{ secondary_array }}"
        api_token: "{{ secondary_array_token }}"
        state: copy

    
