- name: Create a protection group
  hosts: primaryarray
  connection: local
  collections:
  - purestorage.flasharray
  gather_facts: no
 

 
  tasks:
    - name:  Creating protection group and connecting volume
      purefa_pg:
        pgroup: "{{ group }}"
        volume:  
          - "{{ volume_a }}"
          - "{{ volume_b }}"
        fa_url: "{{ primary_array }}"
        api_token: "{{ primary_array_token }}"
