- name: Create a protection group snapshot
  hosts: primaryarray
  connection: local
  collections:
  - purestorage.flasharray
  gather_facts: no



  tasks:
    - name:  Creating a protection group snapshot with suffix app_recovery_CBS
      purefa_pgsnap:
        name: "{{ group }}"
        suffix: "{{ suff }}"
        fa_url: "{{ primary_array }}"
        api_token: "{{ primary_array_token }}"
        state: present
