- name: Create a remote copy of a volume using it's protection group
  hosts: 10.226.116.122
  connection: local
  collections:
  - purestorage.flasharray
  gather_facts: no

  tasks:
    - name:  Create a replicated protection group
      purefa_pg:
        pgroup: foobar
        volume: 
          - andyscorevolume
        fa_url: 10.226.116.122
        api_token: 4ac5c338-a688-3c77-d6cb-dcfd3a5b2424
