- name: add target array
  hosts: primaryarray
  connection: local
  collections:
  - purestorage.flasharray
  gather_facts: no
  
  tasks:
    - name: Connecting target array RedDotX to protection group 
      purefa_pg:
        pgroup: "{{ group }}"
        target: 
          - "{{ target }}"
        fa_url: "{{ primary_array }}"
        api_token: "{{ primary_array_token }}"
