- name: add target array
  hosts: 10.226.116.122
  connection: local
  collections:
  - purestorage.flasharray
  gather_facts: no

  tasks:
    - name: Connecting target array RedDotX to protection group 
      purefa_pg:
        pgroup: apprecoveryCBS
        target: 
          - RedDotX
        fa_url: 10.226.116.122
        api_token: 4ac5c338-a688-3c77-d6cb-dcfd3a5b2424
